### ISSUE TITLE
Problemas com o Login

### ISSUE THREAD

**Issue by lucas-rabelo** [APIBrasil/apigratis-chatopen#1]
Olá, eu baixei o código e segui o passo a passo do Readme, porém não consigo entrar na aplicação. Eu recebo no JSON as informações de que foui logado com sucesso, mas não consigo sair da tela de autenticação. O que pode ser que estou fazendo errado?

**Comment by jhowbhz** [comment]
Poderia postar o que acontece, um video ou foto talvez? para eu tentar te ajudar. Abs!

**Comment by lucas-rabelo** [comment]
![erro_apigratis](https://user-images.githubusercontent.com/65088031/221847823-89203727-5de2-4f36-8bcc-e957e5812159.png)

**Comment by jhowbhz** [comment]
Corrigido mestre!

**Comment by jhowbhz** [comment]
> ![erro_apigratis](https://user-images.githubusercontent.com/65088031/221847823-89203727-5de2-4f36-8bcc-e957e5812159.png)

Foi corrigido nesse commit
https://github.com/APIBrasil/apigratis-chatopen/commit/cc53a421bb0459fbf53a1d845b7f5b964bc0e37e
